# Generated by Django 5.2 on 2025-05-13 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('colorList', '0001_initial'),
        ('proSize', '0002_remove_productsize_name_productsize_category'),
        ('type', '0001_initial'),
        ('weblink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colorList.color')),
                ('link_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblink.weblink')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proSize.productsize')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.type')),
            ],
        ),
    ]
