# Generated by Django 5.2 on 2025-05-13 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proSize', '0002_remove_productsize_name_productsize_category'),
        ('product', '0004_alter_product_pro_name_alter_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proSize.productsize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
