# Generated by Django 5.1.2 on 2025-05-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_size_product_size_group_product_selected_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size_group',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selected_size',
        ),
    ]
