# Generated by Django 5.1.2 on 2025-05-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_size_group_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='selected_size',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
