# Generated by Django 5.1.2 on 2025-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_size_product_selected_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selected_size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
