# Generated by Django 5.2 on 2025-05-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_story_img', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('card_1_img', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('card_2_img', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('card_3_img', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('card_4_img', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('designer_img', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_top_img', models.ImageField(blank=True, null=True, upload_to='contact/')),
                ('contact_bottom_img', models.ImageField(blank=True, null=True, upload_to='contact/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ph_number', models.CharField(max_length=20, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
