# Generated by Django 5.2 on 2025-05-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='review_pics/')),
                ('message', models.TextField()),
                ('point', models.IntegerField()),
            ],
        ),
    ]
