# Generated by Django 5.2 on 2025-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logo', '0002_logo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
