# Generated by Django 5.1.2 on 2025-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='client',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='craft',
            name='projects',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='craft',
            name='year',
            field=models.BigIntegerField(default=0),
        ),
    ]
