# Generated by Django 5.2 on 2025-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200, null=True)),
                ('ph_number', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('facebook_url', models.CharField(max_length=200, null=True)),
                ('instagram_url', models.CharField(max_length=200, null=True)),
                ('youtube_url', models.CharField(max_length=200, null=True)),
                ('whatsapp_url', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
