# Generated by Django 5.2 on 2025-04-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(null=True, upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Banner_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
