# Generated by Django 5.2 on 2025-05-17 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0010_alter_product_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('name', models.TextField(max_length=200, null=True)),
                ('phone_number', models.BigIntegerField(default=0, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
                ('Product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='product.product')),
            ],
        ),
    ]
