# Generated by Django 5.2 on 2025-05-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquirie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiriesmodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
