# Generated by Django 5.2 on 2025-05-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proSize', '0002_remove_productsize_name_productsize_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='sizes',
            field=models.CharField(max_length=100),
        ),
    ]
