# Generated by Django 5.2 on 2025-05-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('proSize', '0003_alter_productsize_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('category', 'sizes')},
        ),
    ]
