# Generated by Django 5.1.2 on 2025-05-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('proSize', '0005_alter_productsize_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='sizes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('category', 'sizes')},
        ),
    ]
