# Generated by Django 5.1.2 on 2025-05-14 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proSize', '0006_alter_productsize_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='productsize',
            name='sizes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proSize.category'),
        ),
    ]
