# Generated by Django 5.1.2 on 2025-05-14 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('proSize', '0007_category_alter_productsize_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='sizes',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
