# Generated by Django 5.1.2 on 2025-05-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proSize', '0008_alter_productsize_category_alter_productsize_sizes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together=set(),
        ),
    ]
